#!/bin/bash

upsearch () {
  found=0
  slashes=${PWD//[^\/]/}
  directory="$PWD"
  for (( n=${#slashes}; n>0; --n ))
  do
    test -e "$directory/$1" && found=1 && return 
    directory="$directory/.."
  done
}

upsearch "bench.sh"

if [ $found -eq 1 ]
  then

    cd $directory
    ./bench.sh $@

else

    echo "bench.sh file not found."

fi
