version: '2'
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: bench-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro